# Site settings 配置站点
title: "小绵羊"
description: "野生程序员一只。"
keyword: "小绵羊,程序员,Java,JavaScript,Node.js,CSS,HTML,Python"
url: "https://xiaomingyang.com"

# if you don't need baseurl, you should leave this value blank.
baseurl: ""

# Navigation links
nav:
    home: "/"
    tags: "/tags.html"

# Footer
footer:
    since: 2015

# Author 配置博主信息
author: "小绵羊"
nickname: "小绵羊"
bio: "野生程序员一只"
avatar: "/assets/img/avatar.jpg"

# Search
search: true

# Night mode
nightMode: false

# Comments 评论功能
comments:
    disqus: false
    disqus_url: ""

# MathJax 公式支持 by Ray-Eldath
mathjax: true

# Share
social-share: true
social-share-items: ["wechat", "weibo", "twitter", "facebook"]

# theme color 主题皮肤
theme-color: "default" # pink or default

# Post header background patterns (when the post no cover): circuitBoard, overlappingCircles, food, glamorous, ticTacToe, seaOfClouds
postPatterns: "seaOfClouds"

# SNS settings 配置社交网站
# url: email, weibo, zhihu, twitter, instagram, juejin, github, douban, facebook, dribble, uicn, jianshu, medium, linkedin
sns:
    github:
    weibo:
    twitter:

# Tags 设置标签
recommend-tags: true # whether or not display recommend-tags on the sidebar
recommend-condition-size: 12 # a tag will be recommended if the size of it is more than this value

#分页设置
paginate: 3
paginate_path: "page:num"

# Build settings
exclude: ["Gemfile", "Gemfile.lock", "CNAME", ".gitignore", "README.md"]

# Markdown
markdown: kramdown
highlighter: rouge
kramdown:
    input: GFM

# Permalink
permalink: /:year/:month/:day/:title.html

# Plugins
plugins: [jekyll-paginate, jekyll-feed]
